version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data
    networks:
      - mynetwork

  redis:
    image: redis
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - mynetwork

  medicine_app:  # Đã đổi tên từ yourapp thành medicine_app
    image: trinhkimlong811/medicine-product:v1
    container_name: medicine_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
